### PR TITLE
fix ModuleText and use Redux thunks

### PR DESCRIPTION
**Pull request by chazkiker2**
# Description

- Fixes # (issue)

# Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

# Change Status

- [x] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)

# How has this been tested?

- [x] Tested locally
- [x] Test suite provides the same results as prior to making changes

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes 
- [x] There are no merge conflicts

### CODE REVIEW

**Review by BUGBOUNTYchrisg8691 — APPROVED** [review]
looks good

**Review by dav1dchang — APPROVED** [review]
Gj Chaz

**Review by simonesquad — APPROVED** [review]
thunks a lot

**Review by sebass482 — APPROVED** [review]
Nice refactoring. Good separation of dispatch logic into moduleActions. All checks passing.

**Pull request merged**
